apiVersion: apps/v1
kind: Deployment
metadata:
  name: allocation
  labels:
    app: allocation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: allocation
  template:
    metadata:
      labels:
        app: allocation
    spec:
      containers:
      - image: abesek/allocation
        name: allocation
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        

