apiVersion: v1
kind: Service
metadata:
  name: allocation
  labels:
    app: allocation
spec:
  selector:
    app: allocation
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
